openapi: 3.1.0
x-stoplight:
  id: fkq76t8k8lmz3
info:
  title: Order
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /order:
    post:
      summary: Create Order
      tags:
        - v1
      responses: {}
      operationId: post-order
      x-stoplight:
        id: pof8vqbpf9adl
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-order
      x-stoplight:
        id: k1ijh8vobymkj
      parameters:
        - schema:
            type: string
          in: header
          name: x-request-id
        - schema:
            type: string
          in: query
          name: id
          description: orderid
components:
  schemas: {}
