openapi: 3.1.0
x-stoplight:
  id: fkq76t8k8lmz3
info:
  title: Order
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /order:
    post:
      summary: Create Order
      tags:
        - v1
      responses: {}
      operationId: post-order
      x-stoplight:
        id: pof8vqbpf9adl
components:
  schemas: {}
